package isocode

var countries = map[Country]countryDetails{
	AD: {Alpha2: "AD", Alpha3: "AND", Flag: "🇦🇩", Name: "Andorra"},
	AE: {Alpha2: "AE", Alpha3: "ARE", Flag: "🇦🇪", Name: "United Arab Emirates"},
	AF: {Alpha2: "AF", Alpha3: "AFG", Flag: "🇦🇫", Name: "Afghanistan"},
	AG: {Alpha2: "AG", Alpha3: "ATG", Flag: "🇦🇬", Name: "Antigua and Barbuda"},
	AI: {Alpha2: "AI", Alpha3: "AIA", Flag: "🇦🇮", Name: "Anguilla"},
	AL: {Alpha2: "AL", Alpha3: "ALB", Flag: "🇦🇱", Name: "Albania"},
	AM: {Alpha2: "AM", Alpha3: "ARM", Flag: "🇦🇲", Name: "Armenia"},
	AO: {Alpha2: "AO", Alpha3: "AGO", Flag: "🇦🇴", Name: "Angola"},
	AQ: {Alpha2: "AQ", Alpha3: "ATA", Flag: "🇦🇶", Name: "Antarctica"},
	AR: {Alpha2: "AR", Alpha3: "ARG", Flag: "🇦🇷", Name: "Argentina"},
	AS: {Alpha2: "AS", Alpha3: "ASM", Flag: "🇦🇸", Name: "American Samoa"},
	AT: {Alpha2: "AT", Alpha3: "AUT", Flag: "🇦🇹", Name: "Austria"},
	AU: {Alpha2: "AU", Alpha3: "AUS", Flag: "🇦🇺", Name: "Australia"},
	AW: {Alpha2: "AW", Alpha3: "ABW", Flag: "🇦🇼", Name: "Aruba"},
	AX: {Alpha2: "AX", Alpha3: "ALA", Flag: "🇦🇽", Name: "Åland Islands"},
	AZ: {Alpha2: "AZ", Alpha3: "AZE", Flag: "🇦🇿", Name: "Azerbaijan"},
	BA: {Alpha2: "BA", Alpha3: "BIH", Flag: "🇧🇦", Name: "Bosnia and Herzegovina"},
	BB: {Alpha2: "BB", Alpha3: "BRB", Flag: "🇧🇧", Name: "Barbados"},
	BD: {Alpha2: "BD", Alpha3: "BGD", Flag: "🇧🇩", Name: "Bangladesh"},
	BE: {Alpha2: "BE", Alpha3: "BEL", Flag: "🇧🇪", Name: "Belgium"},
	BF: {Alpha2: "BF", Alpha3: "BFA", Flag: "🇧🇫", Name: "Burkina Faso"},
	BG: {Alpha2: "BG", Alpha3: "BGR", Flag: "🇧🇬", Name: "Bulgaria"},
	BH: {Alpha2: "BH", Alpha3: "BHR", Flag: "🇧🇭", Name: "Bahrain"},
	BI: {Alpha2: "BI", Alpha3: "BDI", Flag: "🇧🇮", Name: "Burundi"},
	BJ: {Alpha2: "BJ", Alpha3: "BEN", Flag: "🇧🇯", Name: "Benin"},
	BL: {Alpha2: "BL", Alpha3: "BLM", Flag: "🇧🇱", Name: "Saint Barthélemy"},
	BM: {Alpha2: "BM", Alpha3: "BMU", Flag: "🇧🇲", Name: "Bermuda"},
	BN: {Alpha2: "BN", Alpha3: "BRN", Flag: "🇧🇳", Name: "Brunei Darussalam"},
	BO: {Alpha2: "BO", Alpha3: "BOL", Flag: "🇧🇴", Name: "Bolivia (Plurinational State of)"},
	BQ: {Alpha2: "BQ", Alpha3: "BES", Flag: "🇧🇶", Name: "Bonaire, Sint Eustatius and Saba"},
	BR: {Alpha2: "BR", Alpha3: "BRA", Flag: "🇧🇷", Name: "Brazil"},
	BS: {Alpha2: "BS", Alpha3: "BHS", Flag: "🇧🇸", Name: "Bahamas"},
	BT: {Alpha2: "BT", Alpha3: "BTN", Flag: "🇧🇹", Name: "Bhutan"},
	BV: {Alpha2: "BV", Alpha3: "BVT", Flag: "🇧🇻", Name: "Bouvet Island"},
	BW: {Alpha2: "BW", Alpha3: "BWA", Flag: "🇧🇼", Name: "Botswana"},
	BY: {Alpha2: "BY", Alpha3: "BLR", Flag: "🇧🇾", Name: "Belarus"},
	BZ: {Alpha2: "BZ", Alpha3: "BLZ", Flag: "🇧🇿", Name: "Belize"},
	CA: {Alpha2: "CA", Alpha3: "CAN", Flag: "🇨🇦", Name: "Canada"},
	CC: {Alpha2: "CC", Alpha3: "CCK", Flag: "🇨🇨", Name: "Cocos (Keeling) Islands"},
	CD: {Alpha2: "CD", Alpha3: "COD", Flag: "🇨🇩", Name: "Congo, Democratic Republic of the"},
	CF: {Alpha2: "CF", Alpha3: "CAF", Flag: "🇨🇫", Name: "Central African Republic"},
	CG: {Alpha2: "CG", Alpha3: "COG", Flag: "🇨🇬", Name: "Congo"},
	CH: {Alpha2: "CH", Alpha3: "CHE", Flag: "🇨🇭", Name: "Switzerland"},
	CI: {Alpha2: "CI", Alpha3: "CIV", Flag: "🇨🇮", Name: "Côte d'Ivoire"},
	CK: {Alpha2: "CK", Alpha3: "COK", Flag: "🇨🇰", Name: "Cook Islands"},
	CL: {Alpha2: "CL", Alpha3: "CHL", Flag: "🇨🇱", Name: "Chile"},
	CM: {Alpha2: "CM", Alpha3: "CMR", Flag: "🇨🇲", Name: "Cameroon"},
	CN: {Alpha2: "CN", Alpha3: "CHN", Flag: "🇨🇳", Name: "China"},
	CO: {Alpha2: "CO", Alpha3: "COL", Flag: "🇨🇴", Name: "Colombia"},
	CR: {Alpha2: "CR", Alpha3: "CRI", Flag: "🇨🇷", Name: "Costa Rica"},
	CU: {Alpha2: "CU", Alpha3: "CUB", Flag: "🇨🇺", Name: "Cuba"},
	CV: {Alpha2: "CV", Alpha3: "CPV", Flag: "🇨🇻", Name: "Cabo Verde"},
	CW: {Alpha2: "CW", Alpha3: "CUW", Flag: "🇨🇼", Name: "Curaçao"},
	CX: {Alpha2: "CX", Alpha3: "CXR", Flag: "🇨🇽", Name: "Christmas Island"},
	CY: {Alpha2: "CY", Alpha3: "CYP", Flag: "🇨🇾", Name: "Cyprus"},
	CZ: {Alpha2: "CZ", Alpha3: "CZE", Flag: "🇨🇿", Name: "Czechia"},
	DE: {Alpha2: "DE", Alpha3: "DEU", Flag: "🇩🇪", Name: "Germany"},
	DJ: {Alpha2: "DJ", Alpha3: "DJI", Flag: "🇩🇯", Name: "Djibouti"},
	DK: {Alpha2: "DK", Alpha3: "DNK", Flag: "🇩🇰", Name: "Denmark"},
	DM: {Alpha2: "DM", Alpha3: "DMA", Flag: "🇩🇲", Name: "Dominica"},
	DO: {Alpha2: "DO", Alpha3: "DOM", Flag: "🇩🇴", Name: "Dominican Republic"},
	DZ: {Alpha2: "DZ", Alpha3: "DZA", Flag: "🇩🇿", Name: "Algeria"},
	EC: {Alpha2: "EC", Alpha3: "ECU", Flag: "🇪🇨", Name: "Ecuador"},
	EE: {Alpha2: "EE", Alpha3: "EST", Flag: "🇪🇪", Name: "Estonia"},
	EG: {Alpha2: "EG", Alpha3: "EGY", Flag: "🇪🇬", Name: "Egypt"},
	EH: {Alpha2: "EH", Alpha3: "ESH", Flag: "🇪🇭", Name: "Western Sahara"},
	ER: {Alpha2: "ER", Alpha3: "ERI", Flag: "🇪🇷", Name: "Eritrea"},
	ES: {Alpha2: "ES", Alpha3: "ESP", Flag: "🇪🇸", Name: "Spain"},
	ET: {Alpha2: "ET", Alpha3: "ETH", Flag: "🇪🇹", Name: "Ethiopia"},
	FI: {Alpha2: "FI", Alpha3: "FIN", Flag: "🇫🇮", Name: "Finland"},
	FJ: {Alpha2: "FJ", Alpha3: "FJI", Flag: "🇫🇯", Name: "Fiji"},
	FK: {Alpha2: "FK", Alpha3: "FLK", Flag: "🇫🇰", Name: "Falkland Islands (Malvinas)"},
	FM: {Alpha2: "FM", Alpha3: "FSM", Flag: "🇫🇲", Name: "Micronesia (Federated States of)"},
	FO: {Alpha2: "FO", Alpha3: "FRO", Flag: "🇫🇴", Name: "Faroe Islands"},
	FR: {Alpha2: "FR", Alpha3: "FRA", Flag: "🇫🇷", Name: "France"},
	GA: {Alpha2: "GA", Alpha3: "GAB", Flag: "🇬🇦", Name: "Gabon"},
	GB: {Alpha2: "GB", Alpha3: "GBR", Flag: "🇬🇧", Name: "United Kingdom of Great Britain and Northern Ireland"},
	GD: {Alpha2: "GD", Alpha3: "GRD", Flag: "🇬🇩", Name: "Grenada"},
	GE: {Alpha2: "GE", Alpha3: "GEO", Flag: "🇬🇪", Name: "Georgia"},
	GF: {Alpha2: "GF", Alpha3: "GUF", Flag: "🇬🇫", Name: "French Guiana"},
	GG: {Alpha2: "GG", Alpha3: "GGY", Flag: "🇬🇬", Name: "Guernsey"},
	GH: {Alpha2: "GH", Alpha3: "GHA", Flag: "🇬🇭", Name: "Ghana"},
	GI: {Alpha2: "GI", Alpha3: "GIB", Flag: "🇬🇮", Name: "Gibraltar"},
	GL: {Alpha2: "GL", Alpha3: "GRL", Flag: "🇬🇱", Name: "Greenland"},
	GM: {Alpha2: "GM", Alpha3: "GMB", Flag: "🇬🇲", Name: "Gambia"},
	GN: {Alpha2: "GN", Alpha3: "GIN", Flag: "🇬🇳", Name: "Guinea"},
	GP: {Alpha2: "GP", Alpha3: "GLP", Flag: "🇬🇵", Name: "Guadeloupe"},
	GQ: {Alpha2: "GQ", Alpha3: "GNQ", Flag: "🇬🇶", Name: "Equatorial Guinea"},
	GR: {Alpha2: "GR", Alpha3: "GRC", Flag: "🇬🇷", Name: "Greece"},
	GS: {Alpha2: "GS", Alpha3: "SGS", Flag: "🇬🇸", Name: "South Georgia and the South Sandwich Islands"},
	GT: {Alpha2: "GT", Alpha3: "GTM", Flag: "🇬🇹", Name: "Guatemala"},
	GU: {Alpha2: "GU", Alpha3: "GUM", Flag: "🇬🇺", Name: "Guam"},
	GW: {Alpha2: "GW", Alpha3: "GNB", Flag: "🇬🇼", Name: "Guinea-Bissau"},
	GY: {Alpha2: "GY", Alpha3: "GUY", Flag: "🇬🇾", Name: "Guyana"},
	HK: {Alpha2: "HK", Alpha3: "HKG", Flag: "🇭🇰", Name: "Hong Kong"},
	HM: {Alpha2: "HM", Alpha3: "HMD", Flag: "🇭🇲", Name: "Heard Island and McDonald Islands"},
	HN: {Alpha2: "HN", Alpha3: "HND", Flag: "🇭🇳", Name: "Honduras"},
	HR: {Alpha2: "HR", Alpha3: "HRV", Flag: "🇭🇷", Name: "Croatia"},
	HT: {Alpha2: "HT", Alpha3: "HTI", Flag: "🇭🇹", Name: "Haiti"},
	HU: {Alpha2: "HU", Alpha3: "HUN", Flag: "🇭🇺", Name: "Hungary"},
	ID: {Alpha2: "ID", Alpha3: "IDN", Flag: "🇮🇩", Name: "Indonesia"},
	IE: {Alpha2: "IE", Alpha3: "IRL", Flag: "🇮🇪", Name: "Ireland"},
	IL: {Alpha2: "IL", Alpha3: "ISR", Flag: "🇮🇱", Name: "Israel"},
	IM: {Alpha2: "IM", Alpha3: "IMN", Flag: "🇮🇲", Name: "Isle of Man"},
	IN: {Alpha2: "IN", Alpha3: "IND", Flag: "🇮🇳", Name: "India"},
	IO: {Alpha2: "IO", Alpha3: "IOT", Flag: "🇮🇴", Name: "British Indian Ocean Territory"},
	IQ: {Alpha2: "IQ", Alpha3: "IRQ", Flag: "🇮🇶", Name: "Iraq"},
	IR: {Alpha2: "IR", Alpha3: "IRN", Flag: "🇮🇷", Name: "Iran (Islamic Republic of)"},
	IS: {Alpha2: "IS", Alpha3: "ISL", Flag: "🇮🇸", Name: "Iceland"},
	IT: {Alpha2: "IT", Alpha3: "ITA", Flag: "🇮🇹", Name: "Italy"},
	JE: {Alpha2: "JE", Alpha3: "JEY", Flag: "🇯🇪", Name: "Jersey"},
	JM: {Alpha2: "JM", Alpha3: "JAM", Flag: "🇯🇲", Name: "Jamaica"},
	JO: {Alpha2: "JO", Alpha3: "JOR", Flag: "🇯🇴", Name: "Jordan"},
	JP: {Alpha2: "JP", Alpha3: "JPN", Flag: "🇯🇵", Name: "Japan"},
	KE: {Alpha2: "KE", Alpha3: "KEN", Flag: "🇰🇪", Name: "Kenya"},
	KG: {Alpha2: "KG", Alpha3: "KGZ", Flag: "🇰🇬", Name: "Kyrgyzstan"},
	KH: {Alpha2: "KH", Alpha3: "KHM", Flag: "🇰🇭", Name: "Cambodia"},
	KI: {Alpha2: "KI", Alpha3: "KIR", Flag: "🇰🇮", Name: "Kiribati"},
	KM: {Alpha2: "KM", Alpha3: "COM", Flag: "🇰🇲", Name: "Comoros"},
	KN: {Alpha2: "KN", Alpha3: "KNA", Flag: "🇰🇳", Name: "Saint Kitts and Nevis"},
	KP: {Alpha2: "KP", Alpha3: "PRK", Flag: "🇰🇵", Name: "Korea (Democratic People's Republic of)"},
	KR: {Alpha2: "KR", Alpha3: "KOR", Flag: "🇰🇷", Name: "Korea, Republic of"},
	KW: {Alpha2: "KW", Alpha3: "KWT", Flag: "🇰🇼", Name: "Kuwait"},
	KY: {Alpha2: "KY", Alpha3: "CYM", Flag: "🇰🇾", Name: "Cayman Islands"},
	KZ: {Alpha2: "KZ", Alpha3: "KAZ", Flag: "🇰🇿", Name: "Kazakhstan"},
	LA: {Alpha2: "LA", Alpha3: "LAO", Flag: "🇱🇦", Name: "Lao People's Democratic Republic"},
	LB: {Alpha2: "LB", Alpha3: "LBN", Flag: "🇱🇧", Name: "Lebanon"},
	LC: {Alpha2: "LC", Alpha3: "LCA", Flag: "🇱🇨", Name: "Saint Lucia"},
	LI: {Alpha2: "LI", Alpha3: "LIE", Flag: "🇱🇮", Name: "Liechtenstein"},
	LK: {Alpha2: "LK", Alpha3: "LKA", Flag: "🇱🇰", Name: "Sri Lanka"},
	LR: {Alpha2: "LR", Alpha3: "LBR", Flag: "🇱🇷", Name: "Liberia"},
	LS: {Alpha2: "LS", Alpha3: "LSO", Flag: "🇱🇸", Name: "Lesotho"},
	LT: {Alpha2: "LT", Alpha3: "LTU", Flag: "🇱🇹", Name: "Lithuania"},
	LU: {Alpha2: "LU", Alpha3: "LUX", Flag: "🇱🇺", Name: "Luxembourg"},
	LV: {Alpha2: "LV", Alpha3: "LVA", Flag: "🇱🇻", Name: "Latvia"},
	LY: {Alpha2: "LY", Alpha3: "LBY", Flag: "🇱🇾", Name: "Libya"},
	MA: {Alpha2: "MA", Alpha3: "MAR", Flag: "🇲🇦", Name: "Morocco"},
	MC: {Alpha2: "MC", Alpha3: "MCO", Flag: "🇲🇨", Name: "Monaco"},
	MD: {Alpha2: "MD", Alpha3: "MDA", Flag: "🇲🇩", Name: "Moldova, Republic of"},
	ME: {Alpha2: "ME", Alpha3: "MNE", Flag: "🇲🇪", Name: "Montenegro"},
	MF: {Alpha2: "MF", Alpha3: "MAF", Flag: "🇲🇫", Name: "Saint Martin (French part)"},
	MG: {Alpha2: "MG", Alpha3: "MDG", Flag: "🇲🇬", Name: "Madagascar"},
	MH: {Alpha2: "MH", Alpha3: "MHL", Flag: "🇲🇭", Name: "Marshall Islands"},
	MK: {Alpha2: "MK", Alpha3: "MKD", Flag: "🇲🇰", Name: "North Macedonia"},
	ML: {Alpha2: "ML", Alpha3: "MLI", Flag: "🇲🇱", Name: "Mali"},
	MM: {Alpha2: "MM", Alpha3: "MMR", Flag: "🇲🇲", Name: "Myanmar"},
	MN: {Alpha2: "MN", Alpha3: "MNG", Flag: "🇲🇳", Name: "Mongolia"},
	MO: {Alpha2: "MO", Alpha3: "MAC", Flag: "🇲🇴", Name: "Macao"},
	MP: {Alpha2: "MP", Alpha3: "MNP", Flag: "🇲🇵", Name: "Northern Mariana Islands"},
	MQ: {Alpha2: "MQ", Alpha3: "MTQ", Flag: "🇲🇶", Name: "Martinique"},
	MR: {Alpha2: "MR", Alpha3: "MRT", Flag: "🇲🇷", Name: "Mauritania"},
	MS: {Alpha2: "MS", Alpha3: "MSR", Flag: "🇲🇸", Name: "Montserrat"},
	MT: {Alpha2: "MT", Alpha3: "MLT", Flag: "🇲🇹", Name: "Malta"},
	MU: {Alpha2: "MU", Alpha3: "MUS", Flag: "🇲🇺", Name: "Mauritius"},
	MV: {Alpha2: "MV", Alpha3: "MDV", Flag: "🇲🇻", Name: "Maldives"},
	MW: {Alpha2: "MW", Alpha3: "MWI", Flag: "🇲🇼", Name: "Malawi"},
	MX: {Alpha2: "MX", Alpha3: "MEX", Flag: "🇲🇽", Name: "Mexico"},
	MY: {Alpha2: "MY", Alpha3: "MYS", Flag: "🇲🇾", Name: "Malaysia"},
	MZ: {Alpha2: "MZ", Alpha3: "MOZ", Flag: "🇲🇿", Name: "Mozambique"},
	NA: {Alpha2: "NA", Alpha3: "NAM", Flag: "🇳🇦", Name: "Namibia"},
	NC: {Alpha2: "NC", Alpha3: "NCL", Flag: "🇳🇨", Name: "New Caledonia"},
	NE: {Alpha2: "NE", Alpha3: "NER", Flag: "🇳🇪", Name: "Niger"},
	NF: {Alpha2: "NF", Alpha3: "NFK", Flag: "🇳🇫", Name: "Norfolk Island"},
	NG: {Alpha2: "NG", Alpha3: "NGA", Flag: "🇳🇬", Name: "Nigeria"},
	NI: {Alpha2: "NI", Alpha3: "NIC", Flag: "🇳🇮", Name: "Nicaragua"},
	NL: {Alpha2: "NL", Alpha3: "NLD", Flag: "🇳🇱", Name: "Netherlands"},
	NO: {Alpha2: "NO", Alpha3: "NOR", Flag: "🇳🇴", Name: "Norway"},
	NP: {Alpha2: "NP", Alpha3: "NPL", Flag: "🇳🇵", Name: "Nepal"},
	NR: {Alpha2: "NR", Alpha3: "NRU", Flag: "🇳🇷", Name: "Nauru"},
	NU: {Alpha2: "NU", Alpha3: "NIU", Flag: "🇳🇺", Name: "Niue"},
	NZ: {Alpha2: "NZ", Alpha3: "NZL", Flag: "🇳🇿", Name: "New Zealand"},
	OM: {Alpha2: "OM", Alpha3: "OMN", Flag: "🇴🇲", Name: "Oman"},
	PA: {Alpha2: "PA", Alpha3: "PAN", Flag: "🇵🇦", Name: "Panama"},
	PE: {Alpha2: "PE", Alpha3: "PER", Flag: "🇵🇪", Name: "Peru"},
	PF: {Alpha2: "PF", Alpha3: "PYF", Flag: "🇵🇫", Name: "French Polynesia"},
	PG: {Alpha2: "PG", Alpha3: "PNG", Flag: "🇵🇬", Name: "Papua New Guinea"},
	PH: {Alpha2: "PH", Alpha3: "PHL", Flag: "🇵🇭", Name: "Philippines"},
	PK: {Alpha2: "PK", Alpha3: "PAK", Flag: "🇵🇰", Name: "Pakistan"},
	PL: {Alpha2: "PL", Alpha3: "POL", Flag: "🇵🇱", Name: "Poland"},
	PM: {Alpha2: "PM", Alpha3: "SPM", Flag: "🇵🇲", Name: "Saint Pierre and Miquelon"},
	PN: {Alpha2: "PN", Alpha3: "PCN", Flag: "🇵🇳", Name: "Pitcairn"},
	PR: {Alpha2: "PR", Alpha3: "PRI", Flag: "🇵🇷", Name: "Puerto Rico"},
	PS: {Alpha2: "PS", Alpha3: "PSE", Flag: "🇵🇸", Name: "Palestine, State of"},
	PT: {Alpha2: "PT", Alpha3: "PRT", Flag: "🇵🇹", Name: "Portugal"},
	PW: {Alpha2: "PW", Alpha3: "PLW", Flag: "🇵🇼", Name: "Palau"},
	PY: {Alpha2: "PY", Alpha3: "PRY", Flag: "🇵🇾", Name: "Paraguay"},
	QA: {Alpha2: "QA", Alpha3: "QAT", Flag: "🇶🇦", Name: "Qatar"},
	RE: {Alpha2: "RE", Alpha3: "REU", Flag: "🇷🇪", Name: "Réunion"},
	RO: {Alpha2: "RO", Alpha3: "ROU", Flag: "🇷🇴", Name: "Romania"},
	RS: {Alpha2: "RS", Alpha3: "SRB", Flag: "🇷🇸", Name: "Serbia"},
	RU: {Alpha2: "RU", Alpha3: "RUS", Flag: "🇷🇺", Name: "Russian Federation"},
	RW: {Alpha2: "RW", Alpha3: "RWA", Flag: "🇷🇼", Name: "Rwanda"},
	SA: {Alpha2: "SA", Alpha3: "SAU", Flag: "🇸🇦", Name: "Saudi Arabia"},
	SB: {Alpha2: "SB", Alpha3: "SLB", Flag: "🇸🇧", Name: "Solomon Islands"},
	SC: {Alpha2: "SC", Alpha3: "SYC", Flag: "🇸🇨", Name: "Seychelles"},
	SD: {Alpha2: "SD", Alpha3: "SDN", Flag: "🇸🇩", Name: "Sudan"},
	SE: {Alpha2: "SE", Alpha3: "SWE", Flag: "🇸🇪", Name: "Sweden"},
	SG: {Alpha2: "SG", Alpha3: "SGP", Flag: "🇸🇬", Name: "Singapore"},
	SH: {Alpha2: "SH", Alpha3: "SHN", Flag: "🇸🇭", Name: "Saint Helena, Ascension and Tristan da Cunha"},
	SI: {Alpha2: "SI", Alpha3: "SVN", Flag: "🇸🇮", Name: "Slovenia"},
	SJ: {Alpha2: "SJ", Alpha3: "SJM", Flag: "🇸🇯", Name: "Svalbard and Jan Mayen"},
	SK: {Alpha2: "SK", Alpha3: "SVK", Flag: "🇸🇰", Name: "Slovakia"},
	SL: {Alpha2: "SL", Alpha3: "SLE", Flag: "🇸🇱", Name: "Sierra Leone"},
	SM: {Alpha2: "SM", Alpha3: "SMR", Flag: "🇸🇲", Name: "San Marino"},
	SN: {Alpha2: "SN", Alpha3: "SEN", Flag: "🇸🇳", Name: "Senegal"},
	SO: {Alpha2: "SO", Alpha3: "SOM", Flag: "🇸🇴", Name: "Somalia"},
	SR: {Alpha2: "SR", Alpha3: "SUR", Flag: "🇸🇷", Name: "Suriname"},
	SS: {Alpha2: "SS", Alpha3: "SSD", Flag: "🇸🇸", Name: "South Sudan"},
	ST: {Alpha2: "ST", Alpha3: "STP", Flag: "🇸🇹", Name: "Sao Tome and Principe"},
	SV: {Alpha2: "SV", Alpha3: "SLV", Flag: "🇸🇻", Name: "El Salvador"},
	SX: {Alpha2: "SX", Alpha3: "SXM", Flag: "🇸🇽", Name: "Sint Maarten (Dutch part)"},
	SY: {Alpha2: "SY", Alpha3: "SYR", Flag: "🇸🇾", Name: "Syrian Arab Republic"},
	SZ: {Alpha2: "SZ", Alpha3: "SWZ", Flag: "🇸🇿", Name: "Eswatini"},
	TC: {Alpha2: "TC", Alpha3: "TCA", Flag: "🇹🇨", Name: "Turks and Caicos Islands"},
	TD: {Alpha2: "TD", Alpha3: "TCD", Flag: "🇹🇩", Name: "Chad"},
	TF: {Alpha2: "TF", Alpha3: "ATF", Flag: "🇹🇫", Name: "French Southern Territories"},
	TG: {Alpha2: "TG", Alpha3: "TGO", Flag: "🇹🇬", Name: "Togo"},
	TH: {Alpha2: "TH", Alpha3: "THA", Flag: "🇹🇭", Name: "Thailand"},
	TJ: {Alpha2: "TJ", Alpha3: "TJK", Flag: "🇹🇯", Name: "Tajikistan"},
	TK: {Alpha2: "TK", Alpha3: "TKL", Flag: "🇹🇰", Name: "Tokelau"},
	TL: {Alpha2: "TL", Alpha3: "TLS", Flag: "🇹🇱", Name: "Timor-Leste"},
	TM: {Alpha2: "TM", Alpha3: "TKM", Flag: "🇹🇲", Name: "Turkmenistan"},
	TN: {Alpha2: "TN", Alpha3: "TUN", Flag: "🇹🇳", Name: "Tunisia"},
	TO: {Alpha2: "TO", Alpha3: "TON", Flag: "🇹🇴", Name: "Tonga"},
	TR: {Alpha2: "TR", Alpha3: "TUR", Flag: "🇹🇷", Name: "Turkey"},
	TT: {Alpha2: "TT", Alpha3: "TTO", Flag: "🇹🇹", Name: "Trinidad and Tobago"},
	TV: {Alpha2: "TV", Alpha3: "TUV", Flag: "🇹🇻", Name: "Tuvalu"},
	TW: {Alpha2: "TW", Alpha3: "TWN", Flag: "🇹🇼", Name: "Taiwan, Province of China"},
	TZ: {Alpha2: "TZ", Alpha3: "TZA", Flag: "🇹🇿", Name: "Tanzania, United Republic of"},
	UA: {Alpha2: "UA", Alpha3: "UKR", Flag: "🇺🇦", Name: "Ukraine"},
	UG: {Alpha2: "UG", Alpha3: "UGA", Flag: "🇺🇬", Name: "Uganda"},
	UM: {Alpha2: "UM", Alpha3: "UMI", Flag: "🇺🇲", Name: "United States Minor Outlying Islands"},
	US: {Alpha2: "US", Alpha3: "USA", Flag: "🇺🇸", Name: "United States of America"},
	UY: {Alpha2: "UY", Alpha3: "URY", Flag: "🇺🇾", Name: "Uruguay"},
	UZ: {Alpha2: "UZ", Alpha3: "UZB", Flag: "🇺🇿", Name: "Uzbekistan"},
	VA: {Alpha2: "VA", Alpha3: "VAT", Flag: "🇻🇦", Name: "Holy See"},
	VC: {Alpha2: "VC", Alpha3: "VCT", Flag: "🇻🇨", Name: "Saint Vincent and the Grenadines"},
	VE: {Alpha2: "VE", Alpha3: "VEN", Flag: "🇻🇪", Name: "Venezuela (Bolivarian Republic of)"},
	VG: {Alpha2: "VG", Alpha3: "VGB", Flag: "🇻🇬", Name: "Virgin Islands (British)"},
	VI: {Alpha2: "VI", Alpha3: "VIR", Flag: "🇻🇮", Name: "Virgin Islands (U.S.)"},
	VN: {Alpha2: "VN", Alpha3: "VNM", Flag: "🇻🇳", Name: "Viet Nam"},
	VU: {Alpha2: "VU", Alpha3: "VUT", Flag: "🇻🇺", Name: "Vanuatu"},
	WF: {Alpha2: "WF", Alpha3: "WLF", Flag: "🇼🇫", Name: "Wallis and Futuna"},
	WS: {Alpha2: "WS", Alpha3: "WSM", Flag: "🇼🇸", Name: "Samoa"},
	YE: {Alpha2: "YE", Alpha3: "YEM", Flag: "🇾🇪", Name: "Yemen"},
	YT: {Alpha2: "YT", Alpha3: "MYT", Flag: "🇾🇹", Name: "Mayotte"},
	ZA: {Alpha2: "ZA", Alpha3: "ZAF", Flag: "🇿🇦", Name: "South Africa"},
	ZM: {Alpha2: "ZM", Alpha3: "ZMB", Flag: "🇿🇲", Name: "Zambia"},
	ZW: {Alpha2: "ZW", Alpha3: "ZWE", Flag: "🇿🇼", Name: "Zimbabwe"},
}
