package isocode

const (
	AD Country = 20  // AD represents Andorra.
	AE Country = 784 // AE represents the United Arab Emirates.
	AF Country = 4   // AF represents Afghanistan.
	AG Country = 28  // AG represents Antigua and Barbuda.
	AI Country = 660 // AI represents Anguilla.
	AL Country = 8   // AL represents Albania.
	AM Country = 51  // AM represents Armenia.
	AO Country = 24  // AO represents Angola.
	AQ Country = 10  // AQ represents Antarctica.
	AR Country = 32  // AR represents Argentina.
	AS Country = 16  // AS represents American Samoa.
	AT Country = 40  // AT represents Austria.
	AU Country = 36  // AU represents Australia.
	AW Country = 533 // AW represents Aruba.
	AX Country = 248 // AX represents Åland Islands.
	AZ Country = 31  // AZ represents Azerbaijan.
	BA Country = 70  // BA represents Bosnia and Herzegovina.
	BB Country = 52  // BB represents Barbados.
	BD Country = 50  // BD represents Bangladesh.
	BE Country = 56  // BE represents Belgium.
	BF Country = 854 // BF represents Burkina Faso.
	BG Country = 100 // BG represents Bulgaria.
	BH Country = 48  // BH represents Bahrain.
	BI Country = 108 // BI represents Burundi.
	BJ Country = 204 // BJ represents Benin.
	BL Country = 652 // BL represents Saint Barthélemy.
	BM Country = 60  // BM represents Bermuda.
	BN Country = 96  // BN represents Brunei Darussalam.
	BO Country = 68  // BO represents Bolivia (Plurinational State of).
	BQ Country = 535 // BQ represents Bonaire, Sint Eustatius and Saba.
	BR Country = 76  // BR represents Brazil.
	BS Country = 44  // BS represents the Bahamas.
	BT Country = 64  // BT represents Bhutan.
	BV Country = 74  // BV represents Bouvet Island.
	BW Country = 72  // BW represents Botswana.
	BY Country = 112 // BY represents Belarus.
	BZ Country = 84  // BZ represents Belize.
	CA Country = 124 // CA represents Canada.
	CC Country = 166 // CC represents Cocos (Keeling) Islands.
	CD Country = 180 // CD represents Democratic Republic of the Congo.
	CF Country = 140 // CF represents the Central African Republic.
	CG Country = 178 // CG represents Congo.
	CH Country = 756 // CH represents Switzerland.
	CI Country = 384 // CI represents Côte d'Ivoire.
	CK Country = 184 // CK represents Cook Islands.
	CL Country = 152 // CL represents Chile.
	CM Country = 120 // CM represents Cameroon.
	CN Country = 156 // CN represents China.
	CO Country = 170 // CO represents Colombia.
	CR Country = 188 // CR represents Costa Rica.
	CU Country = 192 // CU represents Cuba.
	CV Country = 132 // CV represents Cabo Verde.
	CW Country = 531 // CW represents Curaçao.
	CX Country = 162 // CX represents Christmas Island.
	CY Country = 196 // CY represents Cyprus.
	CZ Country = 203 // CZ represents Czechia.
	DE Country = 276 // DE represents Germany.
	DJ Country = 262 // DJ represents Djibouti.
	DK Country = 208 // DK represents Denmark.
	DM Country = 212 // DM represents Dominica.
	DO Country = 214 // DO represents the Dominican Republic.
	DZ Country = 12  // DZ represents Algeria.
	EC Country = 218 // EC represents Ecuador.
	EE Country = 233 // EE represents Estonia.
	EG Country = 818 // EG represents Egypt.
	EH Country = 732 // EH represents Western Sahara.
	ER Country = 232 // ER represents Eritrea.
	ES Country = 724 // ES represents Spain.
	ET Country = 231 // ET represents Ethiopia.
	FI Country = 246 // FI represents Finland.
	FJ Country = 242 // FJ represents Fiji.
	FK Country = 238 // FK represents the Falkland Islands (Malvinas).
	FM Country = 583 // FM represents Micronesia (Federated States of).
	FO Country = 234 // FO represents Faroe Islands.
	FR Country = 250 // FR represents France.
	GA Country = 266 // GA represents Gabon.
	GB Country = 826 // GB represents the United Kingdom of Great Britain and Northern Ireland.
	GD Country = 308 // GD represents Grenada.
	GE Country = 268 // GE represents Georgia.
	GF Country = 254 // GF represents French Guiana.
	GG Country = 831 // GG represents Guernsey.
	GH Country = 288 // GH represents Ghana.
	GI Country = 292 // GI represents Gibraltar.
	GL Country = 304 // GL represents Greenland.
	GM Country = 270 // GM represents the Gambia.
	GN Country = 324 // GN represents Guinea.
	GP Country = 312 // GP represents Guadeloupe.
	GQ Country = 226 // GQ represents Equatorial Guinea.
	GR Country = 300 // GR represents Greece.
	GS Country = 239 // GS represents South Georgia and the South Sandwich Islands.
	GT Country = 320 // GT represents Guatemala.
	GU Country = 316 // GU represents Guam.
	GW Country = 624 // GW represents Guinea-Bissau.
	GY Country = 328 // GY represents Guyana.
	HK Country = 344 // HK represents Hong Kong.
	HM Country = 334 // HM represents Heard Island and McDonald Islands.
	HN Country = 340 // HN represents Honduras.
	HR Country = 191 // HR represents Croatia.
	HT Country = 332 // HT represents Haiti.
	HU Country = 348 // HU represents Hungary.
	ID Country = 360 // ID represents Indonesia.
	IE Country = 372 // IE represents Ireland.
	IL Country = 376 // IL represents Israel.
	IM Country = 833 // IM represents the Isle of Man.
	IN Country = 356 // IN represents India.
	IO Country = 86  // IO represents British Indian Ocean Territory.
	IQ Country = 368 // IQ represents Iraq.
	IR Country = 364 // IR represents Iran (Islamic Republic of).
	IS Country = 352 // IS represents Iceland.
	IT Country = 380 // IT represents Italy.
	JE Country = 832 // JE represents Jersey.
	JM Country = 388 // JM represents Jamaica.
	JO Country = 400 // JO represents Jordan.
	JP Country = 392 // JP represents Japan.
	KE Country = 404 // KE represents Kenya.
	KG Country = 417 // KG represents Kyrgyzstan.
	KH Country = 116 // KH represents Cambodia.
	KI Country = 296 // KI represents Kiribati.
	KM Country = 174 // KM represents the Comoros.
	KN Country = 659 // KN represents Saint Kitts and Nevis.
	KP Country = 408 // KP represents Korea (Democratic People's Republic of).
	KR Country = 410 // KR represents Korea, Republic of.
	KW Country = 414 // KW represents Kuwait.
	KY Country = 136 // KY represents the Cayman Islands.
	KZ Country = 398 // KZ represents Kazakhstan.
	LA Country = 418 // LA represents Lao People's Democratic Republic.
	LB Country = 422 // LB represents Lebanon.
	LC Country = 662 // LC represents Saint Lucia.
	LI Country = 438 // LI represents Liechtenstein.
	LK Country = 144 // LK represents Sri Lanka.
	LR Country = 430 // LR represents Liberia.
	LS Country = 426 // LS represents Lesotho.
	LT Country = 440 // LT represents Lithuania.
	LU Country = 442 // LU represents Luxembourg.
	LV Country = 428 // LV represents Latvia.
	LY Country = 434 // LY represents Libya.
	MA Country = 504 // MA represents Morocco.
	MC Country = 492 // MC represents Monaco.
	MD Country = 498 // MD represents Moldova, Republic of.
	ME Country = 499 // ME represents Montenegro.
	MF Country = 663 // MF represents Saint Martin (French part).
	MG Country = 450 // MG represents Madagascar.
	MH Country = 584 // MH represents the Marshall Islands.
	MK Country = 807 // MK represents North Macedonia.
	ML Country = 466 // ML represents Mali.
	MM Country = 104 // MM represents Myanmar.
	MN Country = 496 // MN represents Mongolia.
	MO Country = 446 // MO represents Macao.
	MP Country = 580 // MP represents Northern Mariana Islands.
	MQ Country = 474 // MQ represents Martinique.
	MR Country = 478 // MR represents Mauritania.
	MS Country = 500 // MS represents Montserrat.
	MT Country = 470 // MT represents Malta.
	MU Country = 480 // MU represents Mauritius.
	MV Country = 462 // MV represents the Maldives.
	MW Country = 454 // MW represents Malawi.
	MX Country = 484 // MX represents Mexico.
	MY Country = 458 // MY represents Malaysia.
	MZ Country = 508 // MZ represents Mozambique.
	NA Country = 516 // NA represents Namibia.
	NC Country = 540 // NC represents New Caledonia.
	NE Country = 562 // NE represents Niger.
	NF Country = 574 // NF represents Norfolk Island.
	NG Country = 566 // NG represents Nigeria.
	NI Country = 558 // NI represents Nicaragua.
	NL Country = 528 // NL represents the Netherlands.
	NO Country = 578 // NO represents Norway.
	NP Country = 524 // NP represents Nepal.
	NR Country = 520 // NR represents Nauru.
	NU Country = 570 // NU represents Niue.
	NZ Country = 554 // NZ represents New Zealand.
	OM Country = 512 // OM represents Oman.
	PA Country = 591 // PA represents Panama.
	PE Country = 604 // PE represents Peru.
	PF Country = 258 // PF represents French Polynesia.
	PG Country = 598 // PG represents Papua New Guinea.
	PH Country = 608 // PH represents the Philippines.
	PK Country = 586 // PK represents Pakistan.
	PL Country = 616 // PL represents Poland.
	PM Country = 666 // PM represents Saint Pierre and Miquelon.
	PN Country = 612 // PN represents Pitcairn.
	PR Country = 630 // PR represents Puerto Rico.
	PS Country = 275 // PS represents Palestine, State of.
	PT Country = 620 // PT represents Portugal.
	PW Country = 585 // PW represents Palau.
	PY Country = 600 // PY represents Paraguay.
	QA Country = 634 // QA represents Qatar.
	RE Country = 638 // RE represents Réunion.
	RO Country = 642 // RO represents Romania.
	RS Country = 688 // RS represents Serbia.
	RU Country = 643 // RU represents Russian Federation.
	RW Country = 646 // RW represents Rwanda.
	SA Country = 682 // SA represents Saudi Arabia.
	SB Country = 90  // SB represents the Solomon Islands.
	SC Country = 690 // SC represents Seychelles.
	SD Country = 729 // SD represents Sudan.
	SE Country = 752 // SE represents Sweden.
	SG Country = 702 // SG represents Singapore.
	SH Country = 654 // SH represents Saint Helena, Ascension and Tristan da Cunha.
	SI Country = 705 // SI represents Slovenia.
	SJ Country = 744 // SJ represents Svalbard and Jan Mayen.
	SK Country = 703 // SK represents Slovakia.
	SL Country = 694 // SL represents Sierra Leone.
	SM Country = 674 // SM represents San Marino.
	SN Country = 686 // SN represents Senegal.
	SO Country = 706 // SO represents Somalia.
	SR Country = 740 // SR represents Suriname.
	SS Country = 728 // SS represents South Sudan.
	ST Country = 678 // ST represents São Tomé and Príncipe.
	SV Country = 222 // SV represents El Salvador.
	SX Country = 534 // SX represents Sint Maarten (Dutch part).
	SY Country = 760 // SY represents Syrian Arab Republic.
	SZ Country = 748 // SZ represents Eswatini.
	TC Country = 796 // TC represents the Turks and Caicos Islands.
	TD Country = 148 // TD represents Chad.
	TF Country = 260 // TF represents French Southern Territories.
	TG Country = 768 // TG represents Togo.
	TH Country = 764 // TH represents Thailand.
	TJ Country = 762 // TJ represents Tajikistan.
	TK Country = 772 // TK represents Tokelau.
	TL Country = 626 // TL represents Timor-Leste.
	TM Country = 795 // TM represents Turkmenistan.
	TN Country = 788 // TN represents Tunisia.
	TO Country = 776 // TO represents Tonga.
	TR Country = 792 // TR represents Turkey.
	TT Country = 780 // TT represents Trinidad and Tobago.
	TV Country = 798 // TV represents Tuvalu.
	TW Country = 158 // TW represents Taiwan, Province of China.
	TZ Country = 834 // TZ represents Tanzania, United Republic of.
	UA Country = 804 // UA represents Ukraine.
	UG Country = 800 // UG represents Uganda.
	UM Country = 581 // UM represents United States Minor Outlying Islands.
	US Country = 840 // US represents the United States of America.
	UY Country = 858 // UY represents Uruguay.
	UZ Country = 860 // UZ represents Uzbekistan.
	VA Country = 336 // VA represents Holy See.
	VC Country = 670 // VC represents Saint Vincent and the Grenadines.
	VE Country = 862 // VE represents Venezuela (Bolivarian Republic of).
	VG Country = 92  // VG represents the Virgin Islands (British).
	VI Country = 850 // VI represents Virgin Islands (U.S.).
	VN Country = 704 // VN represents Vietnam.
	VU Country = 548 // VU represents Vanuatu.
	WF Country = 876 // WF represents Wallis and Futuna.
	WS Country = 882 // WS represents Samoa.
	YE Country = 887 // YE represents Yemen.
	YT Country = 175 // YT represents Mayotte.
	ZA Country = 710 // ZA represents South Africa.
	ZM Country = 894 // ZM represents Zambia.
	ZW Country = 716 // ZW represents Zimbabwe.
)
