package isocode

var currencies = map[Currency]currencyDetails{
	AED: {Code: "AED", Numeric: 784, Digits: 2, Name: "United Arab Emirates"},
	AFN: {Code: "AFN", Numeric: 971, Digits: 2, Name: "Afghan afghani"},
	ALL: {Code: "ALL", Numeric: 8, Digits: 2, Name: "Albanian lek"},
	AMD: {Code: "AMD", Numeric: 51, Digits: 2, Name: "Armenian dram"},
	ANG: {Code: "ANG", Numeric: 532, Digits: 2, Name: "Netherlands Antillean guilder"},
	AOA: {Code: "AOA", Numeric: 973, Digits: 2, Name: "Angolan kwanza"},
	ARS: {Code: "ARS", Numeric: 32, Digits: 2, Name: "Argentine peso"},
	AUD: {Code: "AUD", Numeric: 36, Digits: 2, Name: "Australian dollar"},
	AWG: {Code: "AWG", Numeric: 533, Digits: 2, Name: "Aruban florin"},
	AZN: {Code: "AZN", Numeric: 944, Digits: 2, Name: "Azerbaijani manat"},
	BAM: {Code: "BAM", Numeric: 977, Digits: 2, Name: "Bosnia and Herzegovina convertible mark"},
	BBD: {Code: "BBD", Numeric: 52, Digits: 2, Name: "Barbados dollar"},
	BDT: {Code: "BDT", Numeric: 50, Digits: 2, Name: "Bangladeshi taka"},
	BGN: {Code: "BGN", Numeric: 975, Digits: 2, Name: "Bulgarian lev"},
	BHD: {Code: "BHD", Numeric: 48, Digits: 3, Name: "Bahraini dinar"},
	BIF: {Code: "BIF", Numeric: 108, Digits: 0, Name: "Burundian franc"},
	BMD: {Code: "BMD", Numeric: 60, Digits: 2, Name: "Bermudian dollar"},
	BND: {Code: "BND", Numeric: 96, Digits: 2, Name: "Brunei dollar"},
	BOB: {Code: "BOB", Numeric: 68, Digits: 2, Name: "Boliviano"},
	BOV: {Code: "BOV", Numeric: 984, Digits: 2, Name: "Bolivian Mvdol (funds code)"},
	BRL: {Code: "BRL", Numeric: 986, Digits: 2, Name: "Brazilian real"},
	BSD: {Code: "BSD", Numeric: 44, Digits: 2, Name: "Bahamian dollar"},
	BTN: {Code: "BTN", Numeric: 64, Digits: 2, Name: "Bhutanese ngultrum"},
	BWP: {Code: "BWP", Numeric: 72, Digits: 2, Name: "Botswana pula"},
	BYN: {Code: "BYN", Numeric: 933, Digits: 2, Name: "Belarusian ruble"},
	BZD: {Code: "BZD", Numeric: 84, Digits: 2, Name: "Belize dollar"},
	CAD: {Code: "CAD", Numeric: 124, Digits: 2, Name: "Canadian dollar"},
	CDF: {Code: "CDF", Numeric: 976, Digits: 2, Name: "Congolese franc"},
	CHE: {Code: "CHE", Numeric: 947, Digits: 2, Name: "WIR euro (complementary currency)"},
	CHF: {Code: "CHF", Numeric: 756, Digits: 2, Name: "Swiss franc"},
	CHW: {Code: "CHW", Numeric: 948, Digits: 2, Name: "WIR franc (complementary currency)"},
	CLF: {Code: "CLF", Numeric: 990, Digits: 4, Name: "Unidad de Fomento (funds code)"},
	CLP: {Code: "CLP", Numeric: 152, Digits: 0, Name: "Chilean peso"},
	COP: {Code: "COP", Numeric: 170, Digits: 2, Name: "Colombian peso"},
	COU: {Code: "COU", Numeric: 970, Digits: 2, Name: "Unidad de Valor Real (UVR)"},
	CRC: {Code: "CRC", Numeric: 188, Digits: 2, Name: "Costa Rican"},
	CUC: {Code: "CUC", Numeric: 931, Digits: 2, Name: "Cuban convertible"},
	CUP: {Code: "CUP", Numeric: 192, Digits: 2, Name: "Cuban peso"},
	CVE: {Code: "CVE", Numeric: 132, Digits: 2, Name: "Cape Verdean escudo"},
	CZK: {Code: "CZK", Numeric: 203, Digits: 2, Name: "Czech koruna"},
	DJF: {Code: "DJF", Numeric: 262, Digits: 0, Name: "Djiboutian franc"},
	DKK: {Code: "DKK", Numeric: 208, Digits: 2, Name: "Danish krone"},
	DOP: {Code: "DOP", Numeric: 214, Digits: 2, Name: "Dominican peso"},
	DZD: {Code: "DZD", Numeric: 12, Digits: 2, Name: "Algerian dinar"},
	EGP: {Code: "EGP", Numeric: 818, Digits: 2, Name: "Egyptian pound"},
	ERN: {Code: "ERN", Numeric: 232, Digits: 2, Name: "Eritrean nakfa"},
	ETB: {Code: "ETB", Numeric: 230, Digits: 2, Name: "Ethiopian birr"},
	EUR: {Code: "EUR", Numeric: 978, Digits: 2, Name: "Euro"},
	FJD: {Code: "FJD", Numeric: 242, Digits: 2, Name: "Fiji dollar"},
	FKP: {Code: "FKP", Numeric: 238, Digits: 2, Name: "Falkland Islands pound"},
	GBP: {Code: "GBP", Numeric: 826, Digits: 2, Name: "Pound sterling"},
	GEL: {Code: "GEL", Numeric: 981, Digits: 2, Name: "Georgian lari"},
	GHS: {Code: "GHS", Numeric: 936, Digits: 2, Name: "Ghanaian cedi"},
	GIP: {Code: "GIP", Numeric: 292, Digits: 2, Name: "Gibraltar pound"},
	GMD: {Code: "GMD", Numeric: 270, Digits: 2, Name: "Gambian dalasi"},
	GNF: {Code: "GNF", Numeric: 324, Digits: 0, Name: "Guinean franc"},
	GTQ: {Code: "GTQ", Numeric: 320, Digits: 2, Name: "Guatemalan quetzal"},
	GYD: {Code: "GYD", Numeric: 328, Digits: 2, Name: "Guyanese dollar"},
	HKD: {Code: "HKD", Numeric: 344, Digits: 2, Name: "Hong Kong dollar"},
	HNL: {Code: "HNL", Numeric: 340, Digits: 2, Name: "Honduran lempira"},
	HTG: {Code: "HTG", Numeric: 332, Digits: 2, Name: "Haitian gourde"},
	HUF: {Code: "HUF", Numeric: 348, Digits: 2, Name: "Hungarian forint"},
	IDR: {Code: "IDR", Numeric: 360, Digits: 2, Name: "Indonesian rupiah"},
	ILS: {Code: "ILS", Numeric: 376, Digits: 2, Name: "Israeli new shekel"},
	INR: {Code: "INR", Numeric: 356, Digits: 2, Name: "Indian rupee"},
	IQD: {Code: "IQD", Numeric: 368, Digits: 3, Name: "Iraqi dinar"},
	IRR: {Code: "IRR", Numeric: 364, Digits: 2, Name: "Iranian rial"},
	ISK: {Code: "ISK", Numeric: 352, Digits: 0, Name: "Icelandic króna (plural: krónur)"},
	JMD: {Code: "JMD", Numeric: 388, Digits: 2, Name: "Jamaican dollar"},
	JOD: {Code: "JOD", Numeric: 400, Digits: 3, Name: "Jordanian dinar"},
	JPY: {Code: "JPY", Numeric: 392, Digits: 0, Name: "Japanese yen"},
	KES: {Code: "KES", Numeric: 404, Digits: 2, Name: "Kenyan shilling"},
	KGS: {Code: "KGS", Numeric: 417, Digits: 2, Name: "Kyrgyzstani som"},
	KHR: {Code: "KHR", Numeric: 116, Digits: 2, Name: "Cambodian riel"},
	KMF: {Code: "KMF", Numeric: 174, Digits: 0, Name: "Comoro franc"},
	KPW: {Code: "KPW", Numeric: 408, Digits: 2, Name: "North Korean won"},
	KRW: {Code: "KRW", Numeric: 410, Digits: 0, Name: "South Korean won"},
	KWD: {Code: "KWD", Numeric: 414, Digits: 3, Name: "Kuwaiti dinar"},
	KYD: {Code: "KYD", Numeric: 136, Digits: 2, Name: "Cayman Islands dollar"},
	KZT: {Code: "KZT", Numeric: 398, Digits: 2, Name: "Kazakhstani tenge"},
	LAK: {Code: "LAK", Numeric: 418, Digits: 2, Name: "Lao kip"},
	LBP: {Code: "LBP", Numeric: 422, Digits: 2, Name: "Lebanese pound"},
	LKR: {Code: "LKR", Numeric: 144, Digits: 2, Name: "Sri Lankan rupee"},
	LRD: {Code: "LRD", Numeric: 430, Digits: 2, Name: "Liberian dollar"},
	LSL: {Code: "LSL", Numeric: 426, Digits: 2, Name: "Lesotho loti"},
	LYD: {Code: "LYD", Numeric: 434, Digits: 3, Name: "Libyan dinar"},
	MAD: {Code: "MAD", Numeric: 504, Digits: 2, Name: "Moroccan dirham"},
	MDL: {Code: "MDL", Numeric: 498, Digits: 2, Name: "Moldovan leu"},
	MGA: {Code: "MGA", Numeric: 969, Digits: 2, Name: "Malagasy ariary"},
	MKD: {Code: "MKD", Numeric: 807, Digits: 2, Name: "Macedonian denar"},
	MMK: {Code: "MMK", Numeric: 104, Digits: 2, Name: "Myanmar kyat"},
	MNT: {Code: "MNT", Numeric: 496, Digits: 2, Name: "Mongolian tögrög"},
	MOP: {Code: "MOP", Numeric: 446, Digits: 2, Name: "Macanese pataca"},
	MRU: {Code: "MRU", Numeric: 929, Digits: 2, Name: "Mauritanian ouguiya"},
	MUR: {Code: "MUR", Numeric: 480, Digits: 2, Name: "Mauritian rupee"},
	MVR: {Code: "MVR", Numeric: 462, Digits: 2, Name: "Maldivian rufiyaa"},
	MWK: {Code: "MWK", Numeric: 454, Digits: 2, Name: "Malawian kwacha"},
	MXN: {Code: "MXN", Numeric: 484, Digits: 2, Name: "Mexican peso"},
	MXV: {Code: "MXV", Numeric: 979, Digits: 2, Name: "Mexican Unidad de Inversion (UDI) (funds code)"},
	MYR: {Code: "MYR", Numeric: 458, Digits: 2, Name: "Malaysian ringgit"},
	MZN: {Code: "MZN", Numeric: 943, Digits: 2, Name: "Mozambican metical"},
	NAD: {Code: "NAD", Numeric: 516, Digits: 2, Name: "Namibian dollar"},
	NGN: {Code: "NGN", Numeric: 566, Digits: 2, Name: "Nigerian naira"},
	NIO: {Code: "NIO", Numeric: 558, Digits: 2, Name: "Nicaraguan córdoba"},
	NOK: {Code: "NOK", Numeric: 578, Digits: 2, Name: "Norwegian krone"},
	NPR: {Code: "NPR", Numeric: 524, Digits: 2, Name: "Nepalese rupee"},
	NZD: {Code: "NZD", Numeric: 554, Digits: 2, Name: "New Zealand dollar"},
	OMR: {Code: "OMR", Numeric: 512, Digits: 3, Name: "Omani rial"},
	PAB: {Code: "PAB", Numeric: 590, Digits: 2, Name: "Panamanian balboa"},
	PEN: {Code: "PEN", Numeric: 604, Digits: 2, Name: "Peruvian sol"},
	PGK: {Code: "PGK", Numeric: 598, Digits: 2, Name: "Papua New"},
	PHP: {Code: "PHP", Numeric: 608, Digits: 2, Name: "Philippine peso"},
	PKR: {Code: "PKR", Numeric: 586, Digits: 2, Name: "Pakistani rupee"},
	PLN: {Code: "PLN", Numeric: 985, Digits: 2, Name: "Polish złoty"},
	PYG: {Code: "PYG", Numeric: 600, Digits: 0, Name: "Paraguayan guaraní"},
	QAR: {Code: "QAR", Numeric: 634, Digits: 2, Name: "Qatari riyal"},
	RON: {Code: "RON", Numeric: 946, Digits: 2, Name: "Romanian leu"},
	RSD: {Code: "RSD", Numeric: 941, Digits: 2, Name: "Serbian dinar"},
	CNY: {Code: "CNY", Numeric: 156, Digits: 2, Name: "Renminbi"},
	RUB: {Code: "RUB", Numeric: 643, Digits: 2, Name: "Russian ruble"},
	RWF: {Code: "RWF", Numeric: 646, Digits: 0, Name: "Rwandan franc"},
	SAR: {Code: "SAR", Numeric: 682, Digits: 2, Name: "Saudi riyal"},
	SBD: {Code: "SBD", Numeric: 90, Digits: 2, Name: "Solomon Islands dollar"},
	SCR: {Code: "SCR", Numeric: 690, Digits: 2, Name: "Seychelles rupee"},
	SDG: {Code: "SDG", Numeric: 938, Digits: 2, Name: "Sudanese pound"},
	SEK: {Code: "SEK", Numeric: 752, Digits: 2, Name: "Swedish krona (plural: kronor)"},
	SGD: {Code: "SGD", Numeric: 702, Digits: 2, Name: "Singapore dollar"},
	SHP: {Code: "SHP", Numeric: 654, Digits: 2, Name: "Saint Helena pound"},
	SLE: {Code: "SLE", Numeric: 925, Digits: 2, Name: "Sierra Leonean leone (new leone)"},
	SLL: {Code: "SLL", Numeric: 694, Digits: 2, Name: "Sierra Leonean leone (old leone)"},
	SOS: {Code: "SOS", Numeric: 706, Digits: 2, Name: "Somali shilling"},
	SRD: {Code: "SRD", Numeric: 968, Digits: 2, Name: "Surinamese dollar"},
	SSP: {Code: "SSP", Numeric: 728, Digits: 2, Name: "South Sudanese pound"},
	STN: {Code: "STN", Numeric: 930, Digits: 2, Name: "São Tomé and Príncipe dobra"},
	SVC: {Code: "SVC", Numeric: 222, Digits: 2, Name: "Salvadoran colón"},
	SYP: {Code: "SYP", Numeric: 760, Digits: 2, Name: "Syrian pound"},
	SZL: {Code: "SZL", Numeric: 748, Digits: 2, Name: "Swazi lilangeni"},
	THB: {Code: "THB", Numeric: 764, Digits: 2, Name: "Thai baht"},
	TJS: {Code: "TJS", Numeric: 972, Digits: 2, Name: "Tajikistani somoni"},
	TMT: {Code: "TMT", Numeric: 934, Digits: 2, Name: "Turkmenistan manat"},
	TND: {Code: "TND", Numeric: 788, Digits: 3, Name: "Tunisian dinar"},
	TOP: {Code: "TOP", Numeric: 776, Digits: 2, Name: "Tongan pa'anga"},
	TRY: {Code: "TRY", Numeric: 949, Digits: 2, Name: "Turkish lira"},
	TTD: {Code: "TTD", Numeric: 780, Digits: 2, Name: "Trinidad and"},
	TWD: {Code: "TWD", Numeric: 901, Digits: 2, Name: "New Taiwan dollar"},
	TZS: {Code: "TZS", Numeric: 834, Digits: 2, Name: "Tanzanian shilling"},
	UAH: {Code: "UAH", Numeric: 980, Digits: 2, Name: "Ukrainian hryvnia"},
	UGX: {Code: "UGX", Numeric: 800, Digits: 0, Name: "Ugandan shilling"},
	USD: {Code: "USD", Numeric: 840, Digits: 2, Name: "United States dollar"},
	USN: {Code: "USN", Numeric: 997, Digits: 2, Name: "United States dollar"},
	UYI: {Code: "UYI", Numeric: 940, Digits: 0, Name: "Uruguay Peso"},
	UYU: {Code: "UYU", Numeric: 858, Digits: 2, Name: "Uruguayan peso"},
	UYW: {Code: "UYW", Numeric: 927, Digits: 4, Name: "Unidad previsional"},
	UZS: {Code: "UZS", Numeric: 860, Digits: 2, Name: "Uzbekistan sum"},
	VED: {Code: "VED", Numeric: 926, Digits: 2, Name: "Venezuelan digital bolívar"},
	VES: {Code: "VES", Numeric: 928, Digits: 2, Name: "Venezuelan sovereign bolívar"},
	VND: {Code: "VND", Numeric: 704, Digits: 0, Name: "Vietnamese đồng"},
	VUV: {Code: "VUV", Numeric: 548, Digits: 0, Name: "Vanuatu vatu"},
	WST: {Code: "WST", Numeric: 882, Digits: 2, Name: "Samoan tala"},
	XAF: {Code: "XAF", Numeric: 950, Digits: 0, Name: "CFA franc"},
	XAG: {Code: "XAG", Numeric: 961, Digits: -1, Name: "Silver (one troy ounce)"},
	XAU: {Code: "XAU", Numeric: 959, Digits: -1, Name: "Gold (one troy ounce)"},
	XBA: {Code: "XBA", Numeric: 955, Digits: -1, Name: "European Composite"},
	XBB: {Code: "XBB", Numeric: 956, Digits: -1, Name: "European Monetary"},
	XBC: {Code: "XBC", Numeric: 957, Digits: -1, Name: "European Unit"},
	XBD: {Code: "XBD", Numeric: 958, Digits: -1, Name: "European Unit"},
	XCD: {Code: "XCD", Numeric: 951, Digits: 2, Name: "East Caribbean dollar"},
	XDR: {Code: "XDR", Numeric: 960, Digits: -1, Name: "Special drawing rights"},
	XOF: {Code: "XOF", Numeric: 952, Digits: 0, Name: "CFA franc"},
	XPD: {Code: "XPD", Numeric: 964, Digits: -1, Name: "Palladium (one troy ounce)"},
	XPF: {Code: "XPF", Numeric: 953, Digits: 0, Name: "CFP franc"},
	XPT: {Code: "XPT", Numeric: 962, Digits: -1, Name: "Platinum (one troy ounce)"},
	XSU: {Code: "XSU", Numeric: 994, Digits: -1, Name: "SUCRE"},
	XTS: {Code: "XTS", Numeric: 963, Digits: -1, Name: "Code reserved for testing"},
	XUA: {Code: "XUA", Numeric: 965, Digits: -1, Name: "ADB Unit of Account"},
	XXX: {Code: "XXX", Numeric: 999, Digits: -1, Name: "No currency"},
	YER: {Code: "YER", Numeric: 886, Digits: 2, Name: "Yemeni rial"},
	ZAR: {Code: "ZAR", Numeric: 710, Digits: 2, Name: "South African rand"},
	ZMW: {Code: "ZMW", Numeric: 967, Digits: 2, Name: "Zambian kwacha"},
	ZWL: {Code: "ZWL", Numeric: 932, Digits: 2, Name: "Zimbabwean dollar (fifth)"},
}
